# Generated by Django 4.1.2 on 2022-10-16 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardStack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('first_language', models.CharField(max_length=2)),
                ('target_language', models.CharField(max_length=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.user')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_target_language', models.BooleanField()),
                ('target_card', models.IntegerField(blank=True, null=True)),
                ('card_stack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.cardstack')),
            ],
        ),
    ]
