# Generated by Django 4.1.2 on 2022-10-16 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email_address', models.CharField(max_length=30)),
                ('user_id', models.CharField(max_length=256)),
            ],
        ),
    ]
